/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as callAnythingSol from "./CallAnything.sol";
export { Encoding__factory } from "./Encoding__factory";
