/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arbitrageSol from "./Arbitrage.sol";
export type { arbitrageSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Migrations } from "./Migrations";
