/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iUniwapV2Router02Sol from "./IUniwapV2Router02.sol";
export type { iUniwapV2Router02Sol };
export type { IUniswapV2ERC20 } from "./IUniswapV2ERC20";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IUniswapV2Router01 } from "./IUniswapV2Router01";
